#!/usr/bin/env bash
# yt-transcript installer.
#
#   curl -fsSL https://raw.githubusercontent.com/kb-gardner/yt-transcript/main/install.sh | bash
#
# Installs the CLI to ~/.yt-transcript, puts a `yt-transcript` wrapper on PATH,
# and (on macOS) builds a Spotlight-launchable "YT Transcript.app". Idempotent:
# re-running updates in place. No sudo, no Homebrew, never auto-installs Node.
set -eu

REPO="kb-gardner/yt-transcript"
# Override hooks (used by the test harness; default to the public GitHub repo).
GIT_URL="${YT_TRANSCRIPT_GIT_URL:-https://github.com/${REPO}.git}"
TARBALL="${YT_TRANSCRIPT_TARBALL:-https://github.com/${REPO}/archive/refs/heads/main.tar.gz}"

DEST="${HOME}/.yt-transcript"
BIN_DIR="${HOME}/.local/bin"
WRAPPER="${BIN_DIR}/yt-transcript"

say()  { printf '%s\n' "$*"; }
info() { printf '  %s\n' "$*"; }
err()  { printf 'Error: %s\n' "$*" >&2; }

# --- 1. Node >= 18 (required; we never install it) --------------------------
if ! command -v node >/dev/null 2>&1; then
  err "Node.js 18+ is required but was not found on your PATH."
  say "Install Node from https://nodejs.org (or 'brew install node' on macOS),"
  say "then re-run this installer."
  exit 1
fi
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0)"
if [ "${NODE_MAJOR:-0}" -lt 18 ]; then
  err "Node 18+ is required (found $(node -v))."
  say "Update Node from https://nodejs.org (or 'brew upgrade node'), then re-run."
  exit 1
fi

# --- 2. Fetch / update the code into ~/.yt-transcript -----------------------
say "Installing yt-transcript into ${DEST} ..."
if command -v git >/dev/null 2>&1; then
  if [ -d "${DEST}/.git" ]; then
    info "Updating existing install (git)"
    git -C "${DEST}" fetch --quiet --depth 1 origin main
    git -C "${DEST}" reset --hard --quiet FETCH_HEAD
  else
    rm -rf "${DEST}"
    git clone --depth 1 --quiet "${GIT_URL}" "${DEST}"
  fi
else
  info "git not found — downloading tarball with curl"
  command -v curl >/dev/null 2>&1 || { err "need either git or curl to install."; exit 1; }
  TMP="$(mktemp -d)"
  curl -fsSL "${TARBALL}" | tar -xz -C "${TMP}"
  SRC="$(find "${TMP}" -maxdepth 1 -type d -name 'yt-transcript-*' | head -1)"
  [ -n "${SRC}" ] || { err "unexpected tarball layout."; rm -rf "${TMP}"; exit 1; }
  rm -rf "${DEST}"
  mkdir -p "${DEST}"
  cp -R "${SRC}/." "${DEST}/"
  rm -rf "${TMP}"
fi

# --- 3. CLI wrapper on PATH -------------------------------------------------
mkdir -p "${BIN_DIR}"
cat > "${WRAPPER}" <<EOF
#!/usr/bin/env bash
# yt-transcript CLI wrapper (generated by install.sh)
exec node "${DEST}/grab.mjs" "\$@"
EOF
chmod +x "${WRAPPER}"
info "CLI wrapper: ${WRAPPER}"

# Is ~/.local/bin already on PATH? If not, tell the user how to add it.
PATH_HINT=""
case ":${PATH}:" in
  *":${BIN_DIR}:"*) : ;;  # already on PATH
  *)
    # Guess the right shell rc without editing it.
    case "${SHELL:-}" in
      *zsh)  RC="${HOME}/.zshrc" ;;
      *bash) if [ "$(uname -s)" = "Darwin" ]; then RC="${HOME}/.bash_profile"; else RC="${HOME}/.bashrc"; fi ;;
      *)     RC="your shell startup file" ;;
    esac
    PATH_HINT="${RC}"
    ;;
esac

# --- 4. macOS Spotlight app (skipped silently on Linux) ---------------------
APP=""
if [ "$(uname -s)" = "Darwin" ] && command -v osacompile >/dev/null 2>&1; then
  NODE_BIN="$(command -v node)"
  APP_DIR="${HOME}/Applications"
  APP="${APP_DIR}/YT Transcript.app"
  mkdir -p "${APP_DIR}"
  TMPD="$(mktemp -d)"
  SCPT="${TMPD}/YT Transcript.applescript"
  # Bake the *installing user's* resolved node path + installed script path into
  # the app (the source file ships with the author's paths as placeholders).
  sed -e "s#^set nodeBin to .*#set nodeBin to \"${NODE_BIN}\"#" \
      -e "s#^set grabScript to .*#set grabScript to \"${DEST}/grab.mjs\"#" \
      "${DEST}/YT Transcript.applescript" > "${SCPT}"
  rm -rf "${APP}"
  if osacompile -o "${APP}" "${SCPT}" >/dev/null 2>&1; then
    info "Spotlight app: ${APP}"
  else
    info "Could not compile the Spotlight app (skipping; the CLI still works)."
    APP=""
  fi
  rm -rf "${TMPD}"
fi

# --- 5. Friendly summary ----------------------------------------------------
say ""
say "yt-transcript installed."
say ""
say "CLI:"
say "  yt-transcript --stdout \"https://youtu.be/VIDEO_ID\"   # print transcript"
say "  yt-transcript \"https://youtu.be/VIDEO_ID\"            # save to ~/Desktop"
say "  yt-transcript --help"
if [ -n "${PATH_HINT}" ]; then
  say ""
  say "NOTE: ${BIN_DIR} is not on your PATH yet. Add this line to ${PATH_HINT}:"
  say "  export PATH=\"\$HOME/.local/bin:\$PATH\""
  say "then open a new terminal (or 'source' that file). Until then, run it as:"
  say "  node \"${DEST}/grab.mjs\" --help"
fi
if [ -n "${APP}" ]; then
  say ""
  say "Spotlight: press Cmd-Space and type \"YT Transcript\" to launch the app."
  say "First launch only: right-click the app in ~/Applications -> Open -> Open"
  say "(it isn't notarized, so macOS asks once)."
fi
